### ISSUE TITLE
Support for Auth convenience functions

### ISSUE THREAD

**Issue by els0r** [fako1024/httpc#18]
Just came across this library "by coincidence" 😏 . It makes the calls from a client definitely more concise, which is highly appreciated.

I'd like to propose a convenience function `AuthDigest(digest string) *Request`, which under the hood calls:

```
params := map[string]string{
    "Authorization": fmt.Sprintf("digest %s", digest),
}
return req.Headers(params)
```
or something along those lines.

**Comment by fako1024** [comment]
Sounds totally reasonable and would be along the lines of the already existing `AuthBasic()`. Will take a look!

**Comment by fako1024** [comment]
On second thought, can you maybe clarify: If you're talking about HTTP Digest Access Authentication as described in [RFC 7616](https://www.rfc-editor.org/rfc/rfc7616.txt) then I'm wondering if just having the convenience function is enough, since the RFC states that the caller should first perform a request, then receive a `HTTP 401` from the server and then compute the digest and perform the query. Just having the aforementioned convenience function would neglect the first part of that flow completely (while with its name implying a functionality that isn't there).

I'm assuming you're doing the flow somewhere outside of `httpc`, right? If so I guess this would boil down to something like a Bearer Auth with a non-standard token prefix (`Digest` instead of `Bearer`). Since we also don't have the former in the package I'm inclined to provide the following:

```
AuthToken(prefix, token string) *Request
AuthBearer(token string) *Request
```
where `AuthBearer` would simply call `AuthToken("Bearer", "<token>").

@els0r Would that fit your use case, or did I misunderstand your use case?

**Comment by els0r** [comment]
It absolutely does. And makes more sense than what I previously posted. Thanks!

**Comment by fako1024** [comment]
@els0r Done. To test it you can `go get` the current main instead of the latest release (I'll create a new tag / release soon once the other issue(s) has / have been cleared).
