### ISSUE TITLE
Honor context cancellations if `Retry` is used

### ISSUE THREAD

**Issue by els0r** [fako1024/httpc#25]
Hello. I just came across a case, where a client uses `RetryBackOff` and sets a retry interval of 
```
httpc.Intervals{
			// retry three times before giving up
			1 * time.Second, 2 * time.Second, 4 * time.Second,
		},
```
The request call takes 7 seconds, no matter whether the context passed to it was cancelled (e.g. via CTRL-C):

```
# time gpctl config -f dummy.conf
^CError running command: failed to update goprobe's runtime configuration: Put "http://127.0.0.1:8145/config": context canceled

real	0m7.017s
user	0m0.015s
sys	0m0.001s
```
I would expect that the library honors the cancellation of `ctx` and also aborts its retry attempts.

Please let me know if this is enough info and whether help on this task is appreciated.

**Comment by els0r** [comment]
Looking at it, https://github.com/fako1024/httpc/blob/main/httpc.go#L413 should probably be wrapped into `select { case <-ctx.Done(): ...; default: 	for i := 0; retryErrFn(resp, err) && i < len(r.retryIntervals); i++ {... } }`

Then, the sleep in [line 420](https://github.com/fako1024/httpc/blob/main/httpc.go#LL420C1-L420C1) (how fitting :D) should also be cancellable.

**Comment by fako1024** [comment]
@els0r Good catch, probably this was overlooked (my guess is that the `ctx` approach was only implemented back in the days because some calling code had / required one, not because someone actually intended to cancel a call - because in most situations you simply don't care as long as you get an error if stuff times out).
That being said, of course it _should_ work. But I think the proposed solution won't work, because wrapping the for loop in a select will prevent any cancellation once we've entered said for loop in the `default` case. I guess a ticker is in order - I'll have a quick look, shouldn't be too hard.

**Comment by fako1024** [comment]
> @els0r Good catch, probably this was overlooked (my guess is that the `ctx` approach was only implemented back in the days because some calling code had / required one, not because someone actually intended to cancel a call - because in most situations you simply don't care as long as you get an error if stuff times out). That being said, of course it _should_ work. But I think the proposed solution won't, because wrapping the for loop in a select will prevent any cancellation once we've entered said for loop in the `default` case (at least when in `time.Sleep()`. I guess a ticker is in order - I'll have a quick look, shouldn't be too hard.

Found a nice solution that's even quite elegant. Will make you a contributor to the repo and fire off a PR for review later - stay tuned!
